### ISSUE TITLE
Přidat ikony

### ISSUE THREAD

**Issue by speedy236** [speedy236/smart-language#18]
http://www.smart-language.com/o-aplikaci-anglictina-iphone

Hodila bych tam nějaké ikonky – je to strohé, když je to jen samostatný text

**Comment by Euvit** [comment]
přidal jsem video v CS verzi

**Comment by speedy236** [comment]
Dobrý nápad, vypadá to líp. Přidat i do ostatních?

**Comment by Euvit** [comment]
ano, můžeme - je to jazykově nezávislé

**Comment by speedy236** [comment]
Hotovo.
