### ISSUE TITLE
Zaoblené ikony

### ISSUE THREAD

**Issue by speedy236** [speedy236/smart-language#19]
http://www.smart-language.com/stahnout-demo

> Proč iOS nemá zaoblené ikony?

Tohle jsem bohužel taky nepochopil. Co ty?

**Comment by Euvit** [comment]
Kolegyně má na mysli zvyklost ikony pro iOS zaoblovat. Jsou tyto možnosti:
- nechat to jak je
- nahrát nové ikony pro iOS
- použít nějakou formátovací HTML/CSS funkci
img
{
  border-radius: 25%;
}

**Comment by speedy236** [comment]
Vyřešeno pomocí border-radius: 10%. Víc procent už ukrajovalo text.
