### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by speedy236** [speedy236/smart-language#22]
Text ve slideru se špatně zarovnává, což je problém zejména na mobilních zařízeních.

Dále je podle kolegyně "chyba v ohraničení slidů". Bohužel nechápu co tím myslí, nevíš to náhodou ty a nemohl bys mi dát i příklad?

**Comment by Euvit** [comment]
Chyba v ohraničení slidů
-	Hned v prvním slidu se ti špatně zarovnává třetí text, tj. Metoda využívá logickou paměť – nejúčinnější druh paměti, není celý vidět, viz obr. Uvodni stranka_nezarovnany text. Tato chyba špatně zarovnaného textu vzniká i u jiných jazyků. Dokonce je chyba i ve druhém slidu, např. u němčiny nejsou vidět všechny aplikace (Ikona Základní angličtina 2 je useklá.) 
- Byl tam k tomu i screenshot

Problém je obecný - delší text by se měl zarovnat (odřídkovat) nebo se delším textům vyhnout a zkrátit. Např. Metoda využívá logickou paměť – nejúčinnější druh paměti -> Metoda využívá logickou paměť

**Comment by speedy236** [comment]
Delší text se normálně odřádkuje. Jenže tohle je ve slideru a smrtelník nad tím nejspíš nemá žádnou moc, takže zkracovaní bude ta cesta, pak na to mrknu, bude to na dýl.
