### ISSUE TITLE
Reorganizace menu

### ISSUE THREAD

**Issue by speedy236** [speedy236/smart-language#23]
> Připadá mi divné, že klik na „Informace“ a „Získat“ mě nikam nepošle. To by mě správně neměl nikam poslat ani klik na „Náhled“ a „Podporu“ – jinak mám pocit, že to nefunguje, jak má.
> Je škoda, že u „Vlastností“, které jsou pod „Informacemi“ nejde vybírat jednotlivé aplikace už přímo v menu
> Celkově jsem rozpačitá z podsekce „Získat“ v menu. Nějak mi připadá úplně navíc, já bych to tam nedávala, v dnešní době lidi vědí, co mají dělat, přes story se dostanou až k aplikaci a tam se vše dozví. Na jiných webech to nemáme a myslím, že fungují, jak mají. Spíš bych tam tedy nechala
> Nějak bych celkově to menu okleštila, připadá mi tam toho hodně a nějak nevím, co kde mám hledat. Klidně bych tam dala:
> Úvod – do textu bych samostatně hodila „O aplikaci“ a „Co získáte“
> Vlastnosti – tam bych dala výběr aplikací, jako je u náhledu
> Jak studovat
> Náhled
> Podpora
> Napsali o nás

Moje otázka zní, souhlasíš s tím takhle a mám to tak udělat?

**Comment by Euvit** [comment]
Zkusil jsem to upravit v CS verzi - myslím, že by to tak mohlo být lepší.

**Comment by speedy236** [comment]
Slovenština hotová - menu, script pro menu, mapa webu

**Comment by Euvit** [comment]
můžeš to udělat nějak automatizovaně pro celý web?

**Comment by speedy236** [comment]
Dokončeno spolu se scripty a mapami.
