### ISSUE TITLE
Špatný počet stažení

### ISSUE THREAD

**Issue by speedy236** [speedy236/smart-language#24]
Chybný počet stažení (nějak netuším, proč se s tím dělám, když to stejně ignorujete). Správně má být 5.322.825 stažení.

**Comment by Euvit** [comment]
u CS verze opraveno

**Comment by Euvit** [comment]
jestli tě napadá řešení, jak to nastavit jednou a pro všechny jazykové verze, nějaké globální proměnná někde, tak navrhni, díky

**Comment by speedy236** [comment]
Napadá mě udělat soubor v rootu a získávat to přes ASP nebo Javascript.

**Comment by speedy236** [comment]
Vyřešeno pomocí ASPu. Číslo je uloženo v /lang/downloads.txt
