### ISSUE TITLE
FB tlačítko

### ISSUE THREAD

**Issue by speedy236** [speedy236/smart-language#3]
### Rozbitý layout
Tlačítko rozbíjí rozložení na telefonech.
Vidím dvě možnosti:
- Vystačit si s Like & Share (bez obrázků a textu)
- Zanechat stávající vzhled za každou cenu a snažit se to vyřešit jinak

### Stránka na kterou směřuje
Všiml jsem si, že pokud chceme zachovat stávající počet "lajků", je potřeba se tvářit jako "i" verze, tzn. tlačítko míří na www.ismartlanguage.com atp. To je problém pro nové lajky, protože FaceBook vyžaduje ještě dvě dodatečná potvrzení.
Možnosti:

- Začít znovu s reálnou adresou a zjednodušit nově příchozím lidem udělení lajků
- Pokračovat s "i" adresou, starým počtem lajků za cenu toho, že nejspíš nebudou přibývat, protože to bude moc složité

Prosím o vyjádření, to rozložení je docela akutní.

**Comment by Euvit** [comment]
Změnil jsem kód FB tlačítka i CS verze jen na Like s počtem a přidal FB ID aplikace. Tak je to potřeba otestovat, jestli to tak bude lepší. Jestli ano, pak aplikovat na všechny jzykové verze

<iframe src="https://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.ismartlanguage.com&width=450&layout=button_count&action=like&size=large&show_faces=false&share=false&height=80&appId=416565508745184" width="450" height="80" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>

Ohledně Potvrzování:

There are integrity and spam-prevention safeguards built into social plugins, and this is one of them. If you have been heavily testing a Like button before launching, you may have inadvertently triggered these safeguards. Additionally certain domains on the internet are more likely to contain spam, so will see the confirm step more often.
This confirmation adds one extra step to the Like button process, but once the like has been confirmed separately by a number of users, it will no longer appear, and the regular Like button will only appear.

**Comment by speedy236** [comment]
Teoreticky to může způsobovat i vkládání přes Iframe / Facebook API. Mrknu na to doma.

**Comment by speedy236** [comment]
Opraveno u všech jazykových verzí. Problém s rozložením zmizel.
