### ISSUE TITLE
EN: vlastnosti - aktivní odkazy

### ISSUE THREAD

**Issue by Euvit** [speedy236/smart-language#6]
Na http://smart-language.com/application-properties je seznam jazyků. Navrhuji jazyky udělat jako odkazy podobně, jako na stránce http://smart-language.com/download-demo

**Comment by speedy236** [comment]
Připraveno na otestování.

**Comment by Euvit** [comment]
jak najdu, kde je to opraveno?

**Comment by speedy236** [comment]
Hotovo
