### ISSUE TITLE
Koupit komplet: poznámka

### ISSUE THREAD

**Issue by Euvit** [speedy236/smart-language#7]
na http://smart-language.com/kaufen chybí německý equivalent textu "Poznámka: Jen při zakoupení celého kurzu získáte nejen cenovou výhodu, ale i dalších 7 speciálních lekcí pro výuku nepravidelných sloves a lekci výuky abecedy, hláskování a výslovnosti."

**Comment by speedy236** [comment]
**Opraveno**

**Comment by speedy236** [comment]
Opraveno
